Leafcutter and dependencies
molgenis/easybuild-easyconfigs pull request #374
Opened 2020-12-09 12:27 UTC by Gerbenvandervries

2020-12-09 12:55 UTC, pneerincx commented on easybuild/easyconfigs/l/Leafcutter/leafcutter-0.2.7-foss-2018b.eb
> +    ('RegTools', '0.5.2', '-foss-2018b-Java-11-LTS',('dummy', '')),
Dit kan niet goed zijn. Je geeft een dummy toolchain op, wat suggereerd dat er geen afhankelijkheid van een toolchain is, maar vervolgens wel foss-2018b in de naam suffix... Ik zou verwachten:
`('RegTools', '0.5.2', '-Java-11-LTS'),`
en dan erft het de foss/2018b van de regel met:
`toolchain = {'name': 'foss', 'version': '2018b'}`

2020-12-09 12:58 UTC, pneerincx commented on easybuild/easyconfigs/r/RegTools/RegTools-0.5.2-foss-2018b-Java-11-LTS.eb
> +moduleclass = 'lib'
Dit klinkt meer als een tool voor in de moduleclass `bio`

2020-12-09 12:59 UTC, pneerincx requested changes
Zie inline comments.

2021-01-21 08:19 UTC, closed without merging

2021-01-21 08:19 UTC, Gerbenvandervries commented
new try