vcf-report v2.4.1 easyconfig
molgenis/easybuild-easyconfigs pull request #417
Opened 2021-06-22 14:49 UTC by dennishendriksen

2021-06-22 16:42 UTC, pneerincx commented on easybuild/easyconfigs/v/vcf-report/vcf-report-v2.4.1-Java-11-LTS.eb
> +toolchain = {'name': 'system', 'version': ''}
https://docs.easybuild.io/en/latest/System_toolchain.html#system-constant

2021-06-22 16:43 UTC, pneerincx requested changes
Why not use the "highly recommended" constant?

2021-06-23 04:50 UTC, dennishendriksen commented
I followed the instructions in the `Using the system compiler` section of https://docs.easybuild.io/en/latest/System_toolchain.html#using-the-system-compiler which states:
```
To use the system toolchain in an easyconfig file, simply use 'system' as toolchain name:

toolchain = {'name': 'system', 'version': ''}
```

2021-06-23 06:20 UTC, pneerincx commented
Please also read the `SYSTEM constant` section directly below `Using the system compiler`.

2021-06-23 06:27 UTC, dennishendriksen commented
I did read it after your first comment. I've picked the initial solution that was described in the documentation. Since the modules have been deployed to multiple environments already I don't think it is worth it to rebuild and go through the process again.

2021-06-29 07:31 UTC, pneerincx approved these changes

2021-07-09 06:18 UTC, dennishendriksen commented
> pneerincx approved these changes 10 days ago
ok, can you merge it as well? ;-)

2021-07-09 08:38 UTC, merged